# This workflows will build a Python Package and store it as an artifact

name: Build and store python package

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install setuptools wheel twine
    - name: Build and publish
      run: |
        python setup.py sdist bdist_whee
    - name: Archive the output
      uses: actions/upload-artifact@v3
      with:
          name: dist
          path: dist/*
          if-no-files-found: error
          retention-days: 7
